---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: flye
description: Assemble Oxford Nanopore reads into contigs with metaFlye
keywords:
  - assembly
  - metagenome
  - nanopore
  - long reads
  - flye
tools:
  - flye:
      description: |
        De novo assembler for single-molecule sequencing reads. `metaFlye` is its
        metagenome mode.
      homepage: https://github.com/mikolmogorov/Flye
      documentation: https://github.com/mikolmogorov/Flye
      doi: 10.1038/s41592-020-00971-x
      licence: ["BSD-3-Clause"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', group:'lake', info:'site1', date:'20260312' ]`
    - reads:
        type: file
        description: Nanopore reads in FastQ format
        pattern: "*.{fastq,fq}{,.gz}"
        ontologies: []
output:
  contigs:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', group:'lake', info:'site1', date:'20260312' ]`
      - "*.contigs.fasta":
          type: file
          description: Assembled contigs
          pattern: "*.contigs.fasta"
          ontologies: []
  info:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', group:'lake', info:'site1', date:'20260312' ]`
      - "*.assembly_info.txt":
          type: file
          description: Per-contig assembly statistics
          pattern: "*.assembly_info.txt"
          ontologies: []
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The process the versions were collected from
      - flye:
          type: string
          description: The tool name
      - "flye --version":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@dsamoht"
maintainers:
  - "@dsamoht"
