report_header_info:
  - Application: "roshab-cli"

show_analysis_paths: False
show_analysis_time: False

kraken:
  top_n: 10

skip_generalstats: true

custom_plot_config:
  nanostat_quality_dist:
    cpswitch_c_active: False
  kraken-top-n-plot:
    cpswitch_c_active: False

top_modules:
  - nanostat
  - kraken
