---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: plot_coverm
description: Plot the per-genome coverage of a group
keywords:
  - visualisation
  - coverage
  - coverm
  - figure
tools:
  - python:
      description: |
        Python is a programming language that lets you work quickly and integrate
        systems more effectively.
      homepage: https://www.python.org
      documentation: https://www.python.org
      licence: ["PSF-2.0"]
      identifier: ""
input:
  - - group_id:
        type: string
        description: Group identifier
    - coverm_tsv:
        type: file
        description: Per-genome coverage table
        pattern: "*.coverm.tsv"
        ontologies: []
  - - samplesheet:
        type: file
        description: The pipeline samplesheet, used for the sampling date and site labels
        pattern: "*.csv"
        ontologies: []
output:
  pdf:
    - - group_id:
          type: string
          description: Group identifier
      - "*.pdf":
          type: file
          description: Genome coverage barplots
          pattern: "*.pdf"
          ontologies: []
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The process the versions were collected from
      - python:
          type: string
          description: The tool name
      - "python --version | sed 's/^Python //'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@dsamoht"
maintainers:
  - "@dsamoht"
