---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: decompress
description: Stage a reference database given as either a directory or a tar.gz archive
keywords:
  - database
  - decompress
  - tar
  - untar
tools:
  - gnu-coreutils:
      description: |
        GNU core utilities, the basic file, shell and text manipulation utilities.
      homepage: https://www.gnu.org/software/coreutils/
      documentation: https://www.gnu.org/software/coreutils/
      licence: ["GPL-3.0"]
      identifier: ""
input:
  - - input_path:
        type: file
        description: Database directory or `.tar.gz`/`.tgz` archive
        ontologies: []
  - - out_name:
        type: string
        description: Name given to the resulting database directory
output:
  db:
    - - "${out_name}":
          type: directory
          description: The database as a directory
authors:
  - "@dsamoht"
maintainers:
  - "@dsamoht"
